### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by neorobo** [idsc-frazzoli/boson_camera#9]
Hi! I am working with a FLIR Boson 640 as well and would like to get ROS driver version working with the BosonLinuxSDK so that we can control NUC events. I'm wondering if this is working yet? I can build boson_camera, but when I run: rosrun boson_camera boson_camera /dev/ttyACM0 

Device set to: /dev/ttyACM0
Capabilities Query: Inappropriate ioctl for device

I realize this is a work in progress but any help would be very appreciated! Thanks.

**Comment by andy2804** [comment]
My first guess here is, that if Capabilities Query returns `Inappropriate ioctl for device` you might have selected the wrong device ID. Do you have several cameras attached to your system?
Try to find the unique ID that your Boson 640 has by using these commands:

    $ cd /dev/v4l/by-id
    $ ls

Your device ID should look somewhat like this:

    /dev/v4l/by-id/usb-FLIR_Boson_XXXXX-video-index0

Try to pass that as argument. The code to establish a serial connection can be also found in the `main.cpp` but we don't use it since you can't use the SDK to stream images properly, but only to set the onboard configuration.

**Comment by alezana** [comment]
@neorobo we updated master.

**Comment by neorobo** [comment]
Amazing guys, everything's working now. I'll see what I can do to use the SDK to control NUC events while using v4l to stream the images. Thanks for your quick response!

**Comment by alezana** [comment]
@neorobo In [here](https://github.com/idsc-frazzoli/boson_camera/tree/master/resources) there is an early attempt but we never integrated it cause we didn't need it. If you want to contribute in improving this ros wrapper, we are looking forward to your pull request :)
